// -- CART ---

export const CART_OPEN = 'CART_OPEN';
export const CART_CLOSE = 'CART_CLOSE';
export const CART_ITEM_REMOVE = 'CART_ITEM_REMOVE';

// Category
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';
// User
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOADING_USER = 'LOADING_USER';
export const LOADING_USER_SUCCESS = 'LOADING_USER_SUCCESS';
export const LOADING_USER_FAIL = 'LOADING_USER_FAIL';
